### ISSUE TITLE
use random background color

### ISSUE THREAD

**Issue by codenoid** [CraveFood/avinit#4]
hi, how to use random background color, thanks

**Comment by mawkee** [comment]
@codenoid sorry for taking this long to reply

By default, `avinit` does kind of a small calculation based on the text you sent. It's "kind of" random between all the choices, but it's consistent. This means that if you have the same set of colours, each time you get an avatar for a specific text, it will always return the same colour.

You can specify the colour pallet you want to work with by invoking:

```
COLORS = ["#aabbcc", "#112233"]
get_svg_avatar(my_text, colors=COLORS)
```

If you want truly random colors, you can build a list of a single color and pass it along. For example:

```
import random

def _get_random_color():
    return "#%06x" % random.randint(0, 0xFFFFFF)

get_svg_avatar(my_text, colors=[_get_random_color()])
```
